### ISSUE TITLE
Startup Delay

### ISSUE THREAD

**Issue by gt-user** [chzesa/tiled-tab-groups#1]
For Tiled Tab Groups v0.16.7
- When you run firefox and after the 1st tab full loaded, if you press the toolbar icon, there is a significant delay to load and show the groups (you may need to press it 3 or 4 times to work /or/ to press F2 once).

**Comment by chzesa** [comment]
Do you have a very large session? The panel is blocked from displaying anything until the addon has fully initialized in the background, which may take a while if you have many tabs in the session.

Other addons may also slow down the loading, since they all share a single thread.

**Comment by gt-user** [comment]
v0.17.3 in Firefox 66.0.1 - problem solved!
Thanks

**Comment by chzesa** [comment]
a897bfcf241ab476f9ed54fd5b91c2c423eab384
