### ISSUE TITLE
Why a new addon?

### ISSUE THREAD

**Issue by gagarine** [chzesa/tiled-tab-groups#11]
Why did you create a news addon instead of a pull request to fix this issue https://github.com/Drive4ik/simple-tab-groups/issues/37

You plan to go in another direction?

**Comment by cryptomilk** [comment]
Simple-Tab-Groups wasn't working with tab hiding for a long time. Tiled Tab Groups implemented it much earlier and the concept of with the nice overview was much better.

**Comment by gagarine** [comment]
I see, but then today it doesn't make really sens anymore.

**Comment by chzesa** [comment]
Tiled tab groups is not a new addon; only the repository is new. Aside from the recently added possibility to reorder groups ttg hasn't had a significant feature addition in months.

**Comment by fturcheti** [comment]
_Should just one tab-groups addon exist?_ This is the thing that doesn't make sense.

I've tested all tab-groups addons and I've settled down with Tiled Tab Groups. It has the features I need in a sleek form. Of course there is space for improvements and occasional problems occur, yet I'm gladly using it for a long time.

Others can prefer Simple Tab Groups or Panorama View or Conex… that's fine. But you can't judge which addons should exist.
