### ISSUE TITLE
"Tab Catch" not working properly

### ISSUE THREAD

**Issue by pintassilgo** [chzesa/tiled-tab-groups#15]
Tested with a fresh new profile on Firefox release, 71.0, without any other addon.

1. Tab Catch rules are lost on browser restart.

2. Matched tab doesn't move immediately to target group, only when I click on another tab then click back on the matched tab (or press Ctrl+Tab then Ctrl+Shift+Tab).

3. When I open a matched tab (while occuring the bug (2)), the hotkey to switch to next/previous group doesn't work until I switch to another tab.

**Comment by chzesa** [comment]
Confirmed, furthermore the groups view doesn't update correctly.

**Comment by chzesa** [comment]
Version 0.18.11 is now available on amo and should have fixed these issues.

**Comment by pintassilgo** [comment]
Confirmed, thank you.
