### ISSUE TITLE
There should be a way to view the list of tabs in stashed groups

### ISSUE THREAD

**Issue by pintassilgo** [chzesa/tiled-tab-groups#18]
Currently, there is no way to know which tabs are in stashed groups. You need to unstash them first.

I think that stashed groups should be visible in Groups View just like the normal groups. Maybe placed on the right side of the page to be isolated from the normal groups. Or maybe with just a different style (like a specific border color around the group or anything like that), which should be easier to implement.

**Comment by chzesa** [comment]
Please check if 85ba787004abb32e81a5a3f063359d2c4d04f19f fulfills this request.

**Comment by pintassilgo** [comment]
Great, thank you.

I think that even with enabled view of stashed groups there should be some "highlight" to make it clear which groups are stashed. Some border, or some backgound-color, or text color...

**Comment by chzesa** [comment]
Stashed tabs have a different appearance in the 0.18.13 version

**Comment by pintassilgo** [comment]
Thank you. I would like the visibility state to be persistent, otherwise every time I want to see stacked groups I will need to click eyes icon. But I understand if you disagree with that.

**Comment by pintassilgo** [comment]
And the stash button is not consistent with stashed state. 
![](https://i.imgur.com/cUUqc3m.png)

`icon-stash` should be replaced by `icon-unstash`

**Comment by chzesa** [comment]
Both added for 0.18.15
