### ISSUE TITLE
"Move Tab to Group" isn't working properly

### ISSUE THREAD

**Issue by pintassilgo** [chzesa/tiled-tab-groups#19]
This is similar to #15.

Now I'm talking about the tab context-menu item.

1. When I move a tab, the hotkey to switch to next/previous group doesn't work until I switch to another tab.

2. If I click to move the current tab, it doesn't move immediately, only when I click on another tab then click back to the moved tab (or press Ctrl+Tab then Ctrl+Shift+Tab).

**Comment by chzesa** [comment]
Fixed in b02f94068e1e0d7237d8f423be91db8533a03d74
