### ISSUE TITLE
ReOrder Groups

### ISSUE THREAD

**Issue by gt-user** [chzesa/tiled-tab-groups#2]
v0.16.7 i cannot reorder groups
a) in tooolbar icon list nor
b) in html page with all groups and their links

**Comment by chzesa** [comment]
Prototype https://github.com/chzesa/tiled-tab-groups/commit/c74f31a4ea947dce096521642222c046bbbf5daf

**Comment by gt-user** [comment]
v0.17.3 in Firefox 66.0.1 - reorder groups working OK!
Thanks
