### ISSUE TITLE
We should be able to open links in another group

### ISSUE THREAD

**Issue by pintassilgo** [chzesa/tiled-tab-groups#22]
There should be an item (submenu) in links contextmenu, similar to what already exists in tabs contextmenu.

**Comment by chzesa** [comment]
812ec49d69878073e2009bc1c44097b938b8c43a

**Comment by pintassilgo** [comment]
Thanks.
https://github.com/chzesa/tiled-tab-groups/blob/812ec49d69878073e2009bc1c44097b938b8c43a/src/js/menu.js#L173-L175

Line 175 should be copied and pasted in line 166 to fix #20:
https://github.com/chzesa/tiled-tab-groups/blob/812ec49d69878073e2009bc1c44097b938b8c43a/src/js/menu.js#L164-L166

**Comment by chzesa** [comment]
I haven't done that to fix #20 because groups view page displays the same context menu entry for moving tabs to different groups and it makes sense to display all groups in that context since tabs from multiple groups can be selected.

**Comment by pintassilgo** [comment]
OK, I hadn't thought of that. But I still think this fix would be better than the current state. Because in Groups View we can drag tabs to other group. By the way, dragging is way more intuitive than using contextmenu. In the other hand, outside Groups View we have no choice but to use tab contextmenu and I think displaying current group makes causes confusion.
