### ISSUE TITLE
Set light/dark theme based on user's system preference

### ISSUE THREAD

**Issue by fturcheti** [chzesa/tiled-tab-groups#23]
The extension color theme could be set to automatically match the user's system preference for light/dark mode.

Below are the references for implementing this functionality:

> The `prefers-color-scheme` CSS media feature is used to detect if the user has requested the system use a light or dark color theme.
> – https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

> The Window interface's `matchMedia()` method returns a new MediaQueryList object representing the parsed results of the specified media query string. The returned MediaQueryList can then be used to determine if the Document matches the media query, or to monitor a document to detect when it matches or stops matching the media query.
> – https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia

So:

```js
window.matchMedia('(prefers-color-scheme: dark)').matches
// should be `true` if the user has set its system to dark mode

window.matchMedia('(prefers-color-scheme: light)').matches
// should be `true` if the user has set its system to light mode
```

And in the Preferences page, under the Appearance section, instead of the current "Use light theme" checkbox the addon could provide a select like this:

```html
<label for="color-theme">Theme:</label>
<select id="color-theme">
  <option value="system">System</option> <!-- matches system color -->
  <option value="light">Light</option> <!-- always light -->
  <option value="dark">Dark</option> <!-- always dark -->
</select>
```

**Comment by chzesa** [comment]
bb9a3f744ffba06e2952a03b84aecf154c87960a

**Comment by fturcheti** [comment]
That was fast! Thanks @chzesa.
