### ISSUE TITLE
Changing group fails with pinned tabs 

### ISSUE THREAD

**Issue by BAKFR** [chzesa/tiled-tab-groups#28]
The problem happens when the last visited tab of a group is a pinned tab.
I use Tree Style Tab, but I guess bug is also present without it.

**Situation:**

I have a pinned tab, somehow associated on *Group 0*. From this pinned tab, I go to another group and browse other tabs.
After a while, I try to go back to the *Group 0* by using the TiledTabGroups icon and Clicking on "Group 0".

**What's happens:**

I'm transported to the pinned tab.
The selected group does not change: the same group is highlighted in the TiledTabGroups menu, and TreeStyleTab does update the tab list.

**What should happen:**

*Group 0* should become the selected group, and Tree Style Tabs should refresh its list as a consequence.

I understand why I'm redirected to the pinned tab (it's the last tab visited in the group), but I think I should be to redirect to the last visited tab excluding pinned tabs.

**Comment by chzesa** [comment]
Updated version should now be available on amo.

**Comment by BAKFR** [comment]
That was quick!

I can confirm it works perfectly now.

Thanks!
