### ISSUE TITLE
Can't move tab using tab context menu

### ISSUE THREAD

**Issue by fturcheti** [chzesa/tiled-tab-groups#3]
Using the current version of the addon I'm unable to move tabs between groups using the tabs context menu.

Browser Console log:

```
<unavailable> src.js:16:13
moz-extension://3cc5b60e-1968-5d4d-b4ca-d7a8115caaa5/external/js-syncqueue/src.js
```

System:

- Tiled Tab Groups: 0.16.7
- Firefox: 67.0b4 (64-bit)
- OS: macOS 10.13.6

**Comment by chzesa** [comment]
https://github.com/chzesa/tiled-tab-groups/commit/d05e6929dc8ae20b5187b6f102a3e797f74ff76f
