### ISSUE TITLE
Add ability to swap groups 

### ISSUE THREAD

**Issue by Jipok** [chzesa/tiled-tab-groups#33]
The ability to open the panel and jump to the desired group by one button is convenient. Unfortunately, the groups now remain in the order of their creation, which is far from a convenient location.

**Comment by chzesa** [comment]
Groups can be rearranged with drag & drop by clicking the button with three stacked horizontal lines in the top right corner of the groups view.

**Comment by Jipok** [comment]
Oh! Very unexpected. I have tried many different ways.
It might be worth adding the ability to drag and drop at least into the pop-up panel.
