### ISSUE TITLE
Reducing the friction on contributions / adoption

### ISSUE THREAD

**Issue by mcataford** [chzesa/tiled-tab-groups#46]
While looking for tab-grouping solutions on Firefox, I stumbled on this extension and it came up ahead of the others as it's open-sourced -- it's always easier to trust something when you can do a quick audit yourself.

One thing that came to mind while checking the extension out though was that there's no details on how users can package it from source (in case they would rather not trust the FF store's hosted version for <reasons>) or can set up a development environment to submit contributions.

Would that be something you'd be interested in facilitating @chzesa? Speaking for self, it would definitely be cool to participate, but first and foremost, I'd like to package it myself before installing it. :sweat_smile: 

I'm down to help make that happen if it's blocked by bandwidth!

**Comment by chzesa** [comment]
No packaging process is required. A development environment can be set up as follows:
1. Clone the repository and its submodules, e.g. `git clone --recursive git@github.com:chzesa/tiled-tab-groups.git`
2. Navigate to `about:debugging#/runtime/this-firefox`, click on `Load a Temporary Add-on`, and select the `manifest.json` file in the `src` folder

The addon file hosted on AMO is just the zipped contents of the `src` folder with metadata added by mozilla. This can be verified by downloading the addon from AMO (right click in the installation button, click save link as), changing the downloaded .xpi file's extension to .zip and extracting it.

**Comment by mcataford** [comment]
Thank you for the details and for adding this information to the documentation!! :pray:
