### ISSUE TITLE
The option to "open in group" in the context menu does not work.

### ISSUE THREAD

**Issue by kaos-55** [chzesa/tiled-tab-groups#48]
When I installed the extension and tested it, I noticed that the option "open in group" found in the context menu does not work. 
When I right click on a link and the context menu opens and I select "open in group" for example group 1, the link does not open in the selected group neither when I select the option "open in new group" it only creates a new group but does not open the link.

**Comment by chzesa** [comment]
This should be fixed by 9eb3ced

**Comment by kaos-55** [comment]
Yes it's fixed, thanks.
Great extension btw.
