### ISSUE TITLE
Moving tab from multiple windows doesn't really works

### ISSUE THREAD

**Issue by gagarine** [chzesa/tiled-tab-groups#6]
I installed this addon on Firefox with 4 windows and around 200 tabs.

Then I tried to move tab to "a main windows" so I can use group.

Tab was disappearing or have a lot of strange behaviors. Hard to really reproduce somethings.

Even switching group start to act strangely (keep the active tab open when switching).

**Comment by chzesa** [comment]
Probably fixed with d7b9e98b6dd2e0ac068d1e6aa95c240efc1a35dd and 70a8961635098d117f95dec32ec1c23e887ec9ba
